# Generated by Django 5.1.1 on 2025-03-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandModel', '0001_initial'),
        ('CarModel', '0003_remove_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='CarModel.car'),
        ),
    ]
