# Generated by Django 5.1.1 on 2025-03-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrandModel', '0002_brand_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='car',
        ),
    ]
