# Generated by Django 5.1.1 on 2025-03-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarModel', '0002_car_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
    ]
