# Generated by Django 5.1.1 on 2025-03-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrandModel', '0003_remove_brand_car'),
        ('CarModel', '0003_remove_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='BrandModel.brand'),
        ),
    ]
